#define(projectScope,string,project scope?)
#define(host,host-ip,host ip?)
#define(httpPort,number,http port?)
#define(exposeHost,host-ip,port expose ip?)
#define(servicePortRangeMin,number,service min available port?)
#define(servicePortRangeMax,number,service max available port?)
#define(etcdHost,string,etcd host?)

debug: true
discovery:
  etcdComponentName: 'etcd'
  scope: $(projectScope)

logger:
  file:
    fileFormat: '[./logs/server-]YYYY-MM-DD[.log]'

node: {}

services:
  http-gateway:
    httpListener:
      port: $(httpPort)
      host: $(host)
      exposeHost: $(exposeHost)

  business:
    tcpListener:
      portRange:
        - $(servicePortRangeMin)
        - $(servicePortRangeMax)
      host: $(host)
      exposeHost: $(exposeHost)

components:
  etcd:
    etcd:
      hosts:
      - $(etcdHost)
    ttl: 20
    prefix: $(projectScope)

workers: {}
