#define(database_type,select:[mysql|postgres|mariadb|sqlite],database database type)
#define(database_host,string,database database host)
#define(database_port,number,database database port)
#define(database_username,string,database database username)
#define(database_password,password,database database password)
#define(database_database,string,database database name)

components:
  database:
    database:
      type: $(database_type)
      host: $(database_host)
      port: $(database_port)
      username*: $(database_username)
      password*: $(database_password)
      database: $(database_database)
workers:
  database-migrate-command:
    components:
      - database
